#!/bin/bash
VHOSTS_ROOT='/var/www/vhosts'
dfltUID='www-data'
dfltGID='www-data'

if (( $(id -u) )); then
 sudo $0 $@
 exit $?
fi

while getopts 'eI:' k; do
 case $k in
  e) flEnableSite=1 ;;
  I) DirectoryIndex="$OPTARG" ;;
 esac
done
shift $((OPTIND-1))

vhost="$1"
declare -A runas=(
	[uid]="${2:-$dfltUID}"
	[gid]="${3:-$dfltGID}"
)

mkdir -p ${VHOSTS_ROOT}/${vhost}/{logs,etc}
chown -R ${runas[uid]}.${runas[gid]} ${VHOSTS_ROOT}/${vhost}
cat >/etc/apache2/sites-available/${vhost}<<EOF
<VirtualHost *:$(fgrep -rH NameVirtualHost /etc/apache2 2>/dev/null | head -1 | sed -nr 's%^.*:[^#]*NameVirtualHost\s+(\*|[0-9.]+):([0-9]+).*$%\2%p')>
#=<COMMON>
	ServerName  ${vhost}
	$([[ $vhost =~ \. ]] && echo -n "ServerAlias ${vhost%%.*}")

	DocumentRoot		${VHOSTS_ROOT}/$vhost/site
	${DirectoryIndex:+DirectoryIndex		$DirectoryIndex}

	AddDefaultCharset 	UTF-8

	LogLevel		warn

	ErrorLog		${VHOSTS_ROOT}/$vhost/logs/error.log
	CustomLog		${VHOSTS_ROOT}/$vhost/logs/access.log combined
#=</COMMON>
</VirtualHost>
EOF

if (( flEnableSite )); then
 a2ensite $vhost && \
  service apache2 reload
fi
